### ISSUE TITLE
Modify installation steps to load the indexer user and password to the keystore.

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh-documentation#6984] opened 2024-01-23 03:35 UTC
### Description

This issue is focused on enhancing the installation documentation by incorporating instructions on how to utilize the newly developed keystore management tool. The tool is designed to facilitate the insertion of values of the indexer user and password.

### Documentation Updates

The following documentation updates should be made:

1. **Installation Guide**: Include a new section detailing the installation and setup of the keystore management tool.

``` bash
$ /var/ossec/bin/wazuh-keystore -f indexer -k username -v admin
$ /var/ossec/bin/wazuh-keystore -f indexer -k password -v admin

```
2. **References**: Remove all references mentioning the user and password under the "indexer" tag in the configuration.

**Comment by Leoquicenoz** [comment] 2024-01-26 00:22
## Update

I start analyzing in which files modifications need to be made

**Comment by Leoquicenoz** [comment] 2024-01-29 02:27
## Update

1. The username and password tags are removed from the indexer template in all the files where they were.
2. The file `/_templates/installations/indexer/common/create_username_password.rst` is created.
3. Changes are made to the installation files where I think they need to be changed.
4. Need to confirm if more files need to be changed (I have a list to confirm with the team).

**Comment by Leoquicenoz** [comment] 2024-01-29 21:37
The ETA is delayed by one day, as there were problems with the PR #6999 and in the end there was not enough time for the review.

**Comment by Leoquicenoz** [comment] 2024-01-30 01:59
## Update

1. A new branch is created, a new PR is created and the changes are uploaded.
2. When compiling with `make text`, some bugs are found which are fixed in two commits 

- [Delete unnecessary underline](https://github.com/wazuh/wazuh-documentation/pull/7000/commits/d6dacea80cd9cab04f13939e254a179c19aa62ca)
- [Fix indentation ERROR](https://github.com/wazuh/wazuh-documentation/pull/7000/commits/ab75a92337cc7cab8f89eb62aa5466c25dcfde96)

3. Compiles without errors or warnings

**Comment by Leoquicenoz** [comment] 2024-01-31 00:40
The ETA is delayed by one day again, because we were concentrating on higher priority issues, the review was not completed today.

**Comment by Leoquicenoz** [comment] 2024-01-31 00:47
## Update

1. Some changes have been made in the explanations, in order to make them clearer for the users.
2. Some spelling and numbering errors in the titles have been fixed.

**Comment by Leoquicenoz** [comment] 2024-01-31 22:51
## Update

Necessary modifications are made to leave the appropriate numbering and format.

![Screenshot from 2024-01-31 13-02-54](https://github.com/wazuh/wazuh-documentation/assets/106568370/7d26a549-85cc-4670-b8c4-7ad91e9fdfaf)

![Screenshot from 2024-01-31 13-31-53](https://github.com/wazuh/wazuh-documentation/assets/106568370/163f149b-9a53-4552-a115-8ad8bec76b0c)

**Comment by ncvicchi** [comment] 2024-02-01 23:19
Issue was finished. Moved ETA just to give time to merge

**Comment by Leoquicenoz** [comment] 2024-02-02 02:17
## Update

1. After the QA team cleared some doubts about the changes to be made in the documentation repository, we went back to the changes that had been made in previous commits and started working on the new changes.

2. The objective of the issue is completed
3. Due to the time at which the changes were finalized, the merge is pending.

**Closed** 2024-02-02 05:18 UTC
Labels: level/task, type/enhancement
