### ISSUE TITLE
elasticsearch: document config requirements during upgrade

### ISSUE THREAD

**Issue by mmccarn** [wazuh/wazuh-documentation#123] opened 2017-12-14 14:39 UTC
Elasticsearch will not start after doing the upgrade on a 2.1 VM appliance (CentOS 7)

Symptom: In step 3 of 'Upgrade Elasticsearch' on this page: https://documentation.wazuh.com/current/installation-guide/upgrading/different_major.html#upgrading-different-major

```
curl https://raw.githubusercontent.com/wazuh/wazuh/3.0/extensions/elasticsearch/wazuh-elastic6-template-alerts.json | curl -XPUT 'http://localhost:9200/_template/wazuh' -H 'Content-Type: application/json' -d @-
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17205  100 17205    0     0  79415      0 --:--:-- --:--:-- --:--:-- 79652
curl: (7) Failed connect to localhost:9200; Connection refused
```

There are new required values in the elasticsearch configuration files, but yum does not overwrite the existing files during the update.

Doing this allows elasticsearch to start, allowing the install to proceed:

```
cd /etc/elasticsearch
mv elasticsearch.yml elasticsearch.yml.save
cp elasticsearch.yml.rpmnew elasticsearch.yml
mv jvm.options jvm.options.save
cp jvm.options.rpmnew jvm.options
```

**Comment by jesusgn90** [comment] 2017-12-14 14:57
Hi @mmccarn , this is not a bug and I think you don't need to modify any files, the problem is related to the starting time that Elasticsearch take. Is true that you need to await some seconds before make a request to the Elasticsearch API (in your situation is `localhost:9200`). Keep in mind this and probably we add to the documentation that user need to await some seconds until Elasticsearch is ready, but I think that your Elasticsearch was started after do that modifications because you waste some seconds doing it, but not started due to them. Thanks for your feedback but please try it without the modifications to ensure that you can start Elasticsearch without do that.

The next time, you can ensure Elasticsearch is ready making this request:

`curl http://localhost:9200/` with no extra arguments, then it returns the version and some more information. When that curl command show you information, then it means Elasticsearch is ready, otherwise is yet starting.

**Comment by mmccarn** [comment] 2017-12-15 12:08
I think you are mistaken about the elasticsearch start time being the problem.

I was unable to proceed with the upgrade specifically because `curl http://localhost:9200` returned `curl: (7) Failed connect to localhost:9200; Connection refused` (as you can see in the results included in my original post).

Here is what I got using the unmodified contents of 'elasticsearch.yml' and 'jvm.options' after running `yum install elasticsearch-6.0.1` (the "●" and the word 'failed' are red):
```
# /etc/init.d/elasticsearch start
Starting elasticsearch (via systemctl):                    [  OK  ]
# /etc/init.d/elasticsearch status
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2017-12-15 05:51:21 CST; 3s ago
     Docs: http://www.elastic.co
  Process: 8800 ExecStart=/usr/share/elasticsearch/bin/elasticsearch -p ${PID_DIR}/elasticsearch.pid --quiet (code=exited, status=1/FAILURE)
 Main PID: 8800 (code=exited, status=1/FAILURE)

Dec 15 05:51:21 wazuh-server elasticsearch[8800]: 2017-12-15 05:51:21,022 main ERROR Null object returned for RollingFile in Appenders.
Dec 15 05:51:21 wazuh-server elasticsearch[8800]: 2017-12-15 05:51:21,022 main ERROR Null object returned for RollingFile in Appenders.
Dec 15 05:51:21 wazuh-server elasticsearch[8800]: 2017-12-15 05:51:21,023 main ERROR Null object returned for RollingFile in Appenders.
Dec 15 05:51:21 wazuh-server elasticsearch[8800]: 2017-12-15 05:51:21,023 main ERROR Unable to locate appender "rolling" for logger config "root"
Dec 15 05:51:21 wazuh-server elasticsearch[8800]: 2017-12-15 05:51:21,023 main ERROR Unable to locate appender "index_indexing_slowlog_rolling" f...g.index"
Dec 15 05:51:21 wazuh-server elasticsearch[8800]: 2017-12-15 05:51:21,023 main ERROR Unable to locate appender "index_search_slowlog_rolling" for...slowlog"
Dec 15 05:51:21 wazuh-server elasticsearch[8800]: 2017-12-15 05:51:21,024 main ERROR Unable to locate appender "deprecation_rolling" for logger c...ecation"
Dec 15 05:51:21 wazuh-server systemd[1]: elasticsearch.service: main process exited, code=exited, status=1/FAILURE
Dec 15 05:51:21 wazuh-server systemd[1]: Unit elasticsearch.service entered failed state.
Dec 15 05:51:22 wazuh-server systemd[1]: elasticsearch.service failed.
Hint: Some lines were ellipsized, use -l to show in full.
```

Here is a summary of my corrective action and the results (the "●" and the words "active (running)" are now green):
```
# cd /etc/elasticsearch
# cp elasticsearch.yml.rpmnew elasticsearch.yml
cp: overwrite ‘elasticsearch.yml’? y
# cp jvm.options.rpmnew jvm.options
cp: overwrite ‘jvm.options’? y
# /etc/init.d/elasticsearch start
Starting elasticsearch (via systemctl):                    [  OK  ]
# /etc/init.d/elasticsearch status
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2017-12-15 05:53:30 CST; 8s ago
     Docs: http://www.elastic.co
 Main PID: 8866 (java)
   CGroup: /system.slice/elasticsearch.service
           └─8866 /bin/java -Xms1g -Xmx1g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+AlwaysPre...

Dec 15 05:53:30 wazuh-server systemd[1]: Started Elasticsearch.
Dec 15 05:53:30 wazuh-server systemd[1]: Starting Elasticsearch...
```

**Comment by jesusgn90** [comment] 2017-12-15 12:22
Hi @mmccarn it sounds to something related to an installation residues due to you are copying _.rpmnew_ files on existing files and that kind of files are generated by __yum__ package manager in order to prevent important files be overwritten. We'll take a look at these kind of situations and let you know if have a better conclusion. This trouble doesn't appear on a fresh installation neither an upgrade installation, so I need bit more time to try to replicate it. One more time, thanks for your feedback.

Best regards,
Jesús.

**Comment by mmccarn** [comment] 2017-12-15 13:20
Thanks.

I don't know that there is anything that needs doing unless the VM appliance maintainers see the same problem.

**Comment by jesusgn90** [comment] 2018-02-15 15:29
More than 30 days have passed and by your last message I understand that we can close this issue, but feel free to create a new issue at any time. Have a nice day.

King regards,
Jesús

**Closed by jesusgn90** 2018-02-15 15:29 UTC
