### ISSUE TITLE
Fix the wazuh-dashboard reference when cloning the repository

### ISSUE THREAD

**Issue by joaquinsgi** [wazuh/wazuh-documentation#8003] opened 2024-12-03 13:42 UTC
| Version |
|:--:|
|  4.9   | 

## Description
Following the steps from Build manually in: https://documentation.wazuh.com/current/development/packaging/generate-dashboard-package.html, it has been found that the documentation has mistakes, because the current version of the documentation is 4.9.2, so the tag v4.9.2 should be used in all the steps

### Steps to reproduce

1. Go to  https://documentation.wazuh.com/current/development/packaging/generate-dashboard-package.html, and check the examples

### Current result

The examples appear with version 4.9.0

### Expected result

The examples need to appear with the current version of the documentation (v4.9.2)

**Comment by asteriscos** [comment] 2024-12-03 14:31
I'm closing this issue as a duplicate of:
- https://github.com/wazuh/wazuh-documentation/issues/7998

**Comment by rauldpm** [comment] 2024-12-03 14:39
Opening this issue again, as we need to fix the branch reference used in the examples, as it is using the 4.9.0 branch which does not exist and leads to confusion, the GitHub reference should be a tag using the latest tag reference, right now it is v4.9.2

**Closed** 2024-12-20 16:43 UTC
Labels: level/task, type/bug
