### ISSUE TITLE
Documentation: <group....> ...</group> required in local_rules.xml

### ISSUE THREAD

**Issue by mmccarn** [wazuh/wazuh-documentation#151] opened 2018-01-28 14:47 UTC
When I follow the instructions for [changing an existing rule](https://documentation.wazuh.com/current/user-manual/ruleset/custom.html#changing-an-existing-rule) in the documentation, I get this error when running ossec-logtest:
```
# /var/ossec/bin/ossec-logtest
...
2018/01/28 08:26:29 ossec-testrule: ERROR: rules_op: Invalid root element "rule".Only "group" is allowed
2018/01/28 08:26:29 ossec-testrule: CRITICAL: (1220): Error loading the rules: 'ruleset/rules/local_rules.xml'.
```

The rule I am changing comes from 0155-dovecot_rules.xml.  If I copy the '<group...> and </group> settings from that file into local_rules.xml, ossec-logtest succeeds:
```
<group name="dovecot,">
<rule id="9706" level="0" overwrite="yes">
  <if_sid>9700</if_sid>
  <match>: Disconnected: </match>
  <description>Dovecot Session Disconnected.</description>
  <group>pci_dss_10.2.5,pci_dss_8.1.5,pci_dss_8.1.8,gpg13_7.1,</group>
</rule>
</group>
```

Todo:
- Document the <group...>...</group> syntax in "[changing an existing rule](https://documentation.wazuh.com/current/user-manual/ruleset/custom.html#changing-an-existing-rule)"

Questions:
- Is the group "name" important -- that is, does it need to match the group name of the original rule?
- If the group name does not need to match, should the group name in "local_rules.xml" be set to something like "local_rules,"?
- If the group name needs to (or should) match, can there be multiple <group...></group> entries in local_rules.xml -- in case I need to change rules from multiple groups?

**Comment by SitoRBJ** [comment] 2018-02-23 11:13
Hello mmccarn,

sorry for the late response. Answering your first question, the "group name" is very important, a rule without group gives you an error like the one you saw before: 

_ERROR: rules_op: Invalid root element "rule".Only "group" is allowed_

We can see that the group is necessary, but the name can be the one you want, it is not necessary to match the group name of the original rule. We recommend that you use a name that is related to the rules it contains. 

For example, we have modified our local rules:


<group name="ssh_brute_force_example, example_2 ">
...
  <rule id="5712" level="11" frequency="6" timeframe="120" ignore="60" overwrite="yes" >
    <if_matched_sid>5710</if_matched_sid>
    <description>sshd: brute force trying to get access to </description>
    <description>the system.</description>
    <same_source_ip />
    <group>authentication_failures,pci_dss_11.4,pci_dss_10.2.4,pci_dss_10.2.5,</group>
  </rule>
...
</group>

Now we provoke a brute force alert for ssh and we can see the rule groups:

![image](https://user-images.githubusercontent.com/8913336/36590945-9c2650b4-1890-11e8-9110-354d524d523f.png)

As we can see, the groups are those that we have defined in the local rules, instead of those of the ruleset (<group name="syslog,sshd,">)

Please let us know if you need further assistance.

Regards.

**Comment by mmccarn** [comment] 2018-02-23 12:31
Thanks!

Would you like me to take a stab at adding this info to the wiki page?

**Comment by SitoRBJ** [comment] 2018-02-26 11:52
Feel free to send whatever you want.

Thanks for the collaboration.

Regards.

**Comment by Smarre** [comment] 2018-04-03 11:13
I assume no-one has done this documentation change yet? I just were wondering about same and arrived to this ticket.

**Comment by pillarsdotnet** [comment] 2018-09-18 17:32
I just ran into this problem.

I'm trying to find documentation describing the allowable syntax of the [local_rules.xml](https://documentation.wazuh.com/current/user-manual/ruleset/custom.html) file.

Apparently, such documentation does not yet exist. except in [the code][https://github.com/wazuh/wazuh/blob/master/src/shared/rules_op.c#L156].

(sigh)

**Comment by pillarsdotnet** [comment] 2018-09-20 22:18
If added, a documentation page describing the local_rules.xml file should be linked [here](https://github.com/wazuh/wazuh-documentation/blob/master/source/user-manual/reference/index.rst).

If I get bored in the next few days I may write one and submit a PR.

**Comment by JuanjiJG** [comment] 2018-11-19 11:53
Hello everybody,

We apologize for the inconvenience caused by the long wait and response times in this issue. I would like to address your questions and concerns regarding this problem.

In response to @mmccarn, as @SitoRBJ said...:
- The `<group>` tag is needed when creating custom rules on the `local_rules.xml` file.
- The `<group>` tag requires the `name` attribute. It's mandatory in order to make it work.
- If one of the previous items is not present, `ossec-logtest` will return an error message, because this is not the appropriate format.
- The `group` tag doesn't require the same name as the rule we're trying to modify. We can use the same groups, or create a new one to distinguish our custom rules from the existing ones.
- The correct format for the group name is a list of items separated by a comma, leaving a comma at the end of the value. For example: `<group name="local,syslog,sshd,">`

This will be added to the documentation. You can track this issue, where we'll include more improvements for the Ruleset documentation, along with these necessary changes: https://github.com/wazuh/wazuh-documentation/issues/590

In response to @pillarsdotnet, currently you can find the syntax for the `local_rules.xml` file here: https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/rules.html

As part of #590, we're updating and modifying the existing documentation to make creating custom rules easier and clearer, with examples and more descriptions for each setting.

Once again, sorry for the inconvenience. We appreciate your comments, feedback and suggestions, and we always want to know what the community has to say about our documentation.

I'll proceed to close this issue and we'll continue on #590. I've collected all the information and requested changes from this thread. Don't hesitate to post new comments if you still have questions or problems with the documentation.

Regards,
Juanjo

**Closed by JuanjiJG** 2018-11-19 11:53 UTC
Labels: new docs
