### ISSUE TITLE
Agent not registering

### ISSUE THREAD

**Issue by 443ca** [wazuh/wazuh-documentation#588] opened 2018-11-08 06:08 UTC
I have loaded two microsoft agents.  Both show as never connected. 

The TCP dump shows the following.
01:01:33.089312 IP 10.0.67.97.62511 > 10.0.67.73.fujitsu-dtcns: UDP, length 85
01:01:37.089733 IP 10.0.67.97.62511 > 10.0.67.73.fujitsu-dtcns: UDP, length 85
01:01:42.090470 IP 10.0.67.97.62511 > 10.0.67.73.fujitsu-dtcns: UDP, length 85
01:01:48.091218 IP 10.0.67.97.62511 > 10.0.67.73.fujitsu-dtcns: UDP, length 85
01:01:51.672579 IP 10.0.67.97.51348 > 10.0.67.73.fujitsu-dtcns: UDP, length 85
01:01:57.673621 IP 10.0.67.97.51348 > 10.0.67.73.fujitsu-dtcns: UDP, length 85
01:02:01.673872 IP 10.0.67.97.51348 > 10.0.67.73.fujitsu-dtcns: UDP, length 85
01:02:06.674677 IP 10.0.67.97.51348 > 10.0.67.73.fujitsu-dtcns: UDP, length 85
01:02:12.675507 IP 10.0.67.97.51348 > 10.0.67.73.fujitsu-dtcns: UDP, length 85
01:02:13.678743 IP 10.0.67.97.65245 > 10.0.67.73.fujitsu-dtcns: UDP, length 85
01:02:19.679748 IP 10.0.67.97.65245 > 10.0.67.73.fujitsu-dtcns: UDP, length 85
01:02:23.680054 IP 10.0.67.97.65245 > 10.0.67.73.fujitsu-dtcns: UDP, length 85
01:02:28.680603 IP 10.0.67.97.65245 > 10.0.67.73.fujitsu-dtcns: UDP, length 85

The test station is 10.0.67.97  and the server is 10.0.67.73.  It seems as if the server receives the packet but then never replies.   I have added the firewall rule to make sure that it is allowing udp 1514,   

The client has the following - 2018/11/08 01:02:45 ossec-agent: INFO: Trying to connect to server (10.0.67.73:1514/udp).
2018/11/08 01:03:06 ossec-agent: WARNING: (4101): Waiting for server reply (not started). Tried: '10.0.67.73'.
2018/11/08 01:03:17 ossec-agent: INFO: Trying to connect to server (10.0.67.73:1514/udp).
2018/11/08 01:03:38 ossec-agent: WARNING: (4101): Waiting for server reply (not started). Tried: '10.0.67.73'.
2018/11/08 01:03:49 ossec-agent: INFO: Trying to connect to server (10.0.67.73:1514/udp).
2018/11/08 01:04:10 ossec-agent: WARNING: (4101): Waiting for server reply (not started). Tried: '10.0.67.73'.
2018/11/08 01:04:21 ossec-agent: INFO: Trying to connect to server (10.0.67.73:1514/udp).
2018/11/08 01:04:42 ossec-agent: WARNING: (4101): Waiting for server reply (not started). Tried: '10.0.67.73'.
2018/11/08 01:04:53 ossec-agent: INFO: Trying to connect to server (10.0.67.73:1514/udp).
2018/11/08 01:05:14 ossec-agent: WARNING: (4101): Waiting for server reply (not started). Tried: '10.0.67.73'.
2018/11/08 01:05:25 ossec-agent: INFO: Trying to connect to server (10.0.67.73:1514/udp).
2018/11/08 01:05:46 ossec-agent: WARNING: (4101): Waiting for server reply (not started). Tried: '10.0.67.73'.
2018/11/08 01:05:57 ossec-agent: INFO: Trying to connect to server (10.0.67.73:1514/udp).
2018/11/08 01:06:18 ossec-agent: WARNING: (4101): Waiting for server reply (not started). Tried: '10.0.67.73'.
2018/11/08 01:06:29 ossec-agent: INFO: Trying to connect to server (10.0.67.73:1514/udp).
2018/11/08 01:06:50 ossec-agent: WARNING: (4101): Waiting for server reply (not started). Tried: '10.0.67.73'.
2018/11/08 01:07:01 ossec-agent: INFO: Trying to connect to server (10.0.67.73:1514/udp).
2018/11/08 01:07:22 ossec-agent: WARNING: (4101): Waiting for server reply (not started). Tried: '10.0.67.73'.
2018/11/08 01:07:33 ossec-agent: INFO: Trying to connect to server (10.0.67.73:1514/udp).
2018/11/08 01:07:54 ossec-agent: WARNING: (4101): Waiting for server reply (not started). Tried: '10.0.67.73'.

**Comment by JuanjiJG** [comment] 2018-11-20 11:01
Hello @443ca, and sorry for the late response.

Apologies for the inconvenience. Let's try to see what might be the cause of your error.

Let's take a look at your Wazuh manager service status using the following commands (executed as `root`):
```
systemctl status wazuh-manager
/var/ossec/bin/ossec-control status
```

This way, we can see if the manager is working properly. If you already registered the agents and there is connectivity between them and the manager, there should not be any major problems except on the manager.

Let me know the results.

Regards,
Juanjo

**Comment by JuanjiJG** [comment] 2018-12-18 14:51
It's been a month since the last response to this issue, so I'll proceed to close it.

Don't hesitate to open a new one if you still have problems or questions about Wazuh.

Regards,
Juanjo

**Closed by JuanjiJG** 2018-12-18 14:51 UTC
Labels: question
